USE [udeo]
GO

/****** Object:  Table [dbo].[DEPARTAMENTO]    Script Date: 6/06/2024 01:06:31 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[DEPARTAMENTO](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[DEPARTAMENTO] [nvarchar](50) NOT NULL,
	[IDPAIS] [int] NOT NULL,
 CONSTRAINT [PK_DEPARTAMENTO] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[DEPARTAMENTO]  WITH CHECK ADD  CONSTRAINT [FK_DEPARTAMENTO_PAIS] FOREIGN KEY([IDPAIS])
REFERENCES [dbo].[PAIS] ([ID])
GO

ALTER TABLE [dbo].[DEPARTAMENTO] CHECK CONSTRAINT [FK_DEPARTAMENTO_PAIS]
GO


