USE [udeo]
GO

/****** Object:  Table [dbo].[INSCRIPCION]    Script Date: 6/06/2024 01:07:56 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[INSCRIPCION](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[CUI] [int] NOT NULL,
	[NOMBRES] [nvarchar](100) NOT NULL,
	[APELLIDOS] [nvarchar](100) NOT NULL,
	[FECHANAC] [date] NOT NULL,
	[TELEFONO] [nvarchar](8) NOT NULL,
	[IDMUNICIPIO] [int] NOT NULL,
	[DOMICILIO] [nvarchar](150) NOT NULL,
	[IDDIVERSIFICADO] [int] NOT NULL,
	[IDLICENCIATURA] [int] NOT NULL,
	[IDJORNADA] [int] NOT NULL,
 CONSTRAINT [PK_INSCRIPCION] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[INSCRIPCION]  WITH CHECK ADD  CONSTRAINT [FK_INSCRIPCION_DIVERSIFICADO] FOREIGN KEY([IDDIVERSIFICADO])
REFERENCES [dbo].[DIVERSIFICADO] ([ID])
GO

ALTER TABLE [dbo].[INSCRIPCION] CHECK CONSTRAINT [FK_INSCRIPCION_DIVERSIFICADO]
GO

ALTER TABLE [dbo].[INSCRIPCION]  WITH CHECK ADD  CONSTRAINT [FK_INSCRIPCION_JORNADA] FOREIGN KEY([IDJORNADA])
REFERENCES [dbo].[JORNADA] ([ID])
GO

ALTER TABLE [dbo].[INSCRIPCION] CHECK CONSTRAINT [FK_INSCRIPCION_JORNADA]
GO

ALTER TABLE [dbo].[INSCRIPCION]  WITH CHECK ADD  CONSTRAINT [FK_INSCRIPCION_LICENCIATURA] FOREIGN KEY([IDLICENCIATURA])
REFERENCES [dbo].[LICENCIATURA] ([ID])
GO

ALTER TABLE [dbo].[INSCRIPCION] CHECK CONSTRAINT [FK_INSCRIPCION_LICENCIATURA]
GO

ALTER TABLE [dbo].[INSCRIPCION]  WITH CHECK ADD  CONSTRAINT [FK_INSCRIPCION_MUNICIPIO] FOREIGN KEY([IDMUNICIPIO])
REFERENCES [dbo].[MUNICIPIO] ([ID])
GO

ALTER TABLE [dbo].[INSCRIPCION] CHECK CONSTRAINT [FK_INSCRIPCION_MUNICIPIO]
GO


