USE [udeo]
GO

/****** Object:  Table [dbo].[LICENCIATURA]    Script Date: 6/06/2024 01:08:32 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[LICENCIATURA](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[LICENCIATURA] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_LICENCIATURA] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


