USE [udeo]
GO

/****** Object:  Table [dbo].[MUNICIPIO]    Script Date: 6/06/2024 01:08:42 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[MUNICIPIO](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[MUNICIPIO] [nvarchar](50) NOT NULL,
	[IDDEPARTAMENTO] [int] NOT NULL,
 CONSTRAINT [PK_MUNICIPIO] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[MUNICIPIO]  WITH CHECK ADD  CONSTRAINT [FK_MUNICIPIO_DEPARTAMENTO] FOREIGN KEY([IDDEPARTAMENTO])
REFERENCES [dbo].[DEPARTAMENTO] ([ID])
GO

ALTER TABLE [dbo].[MUNICIPIO] CHECK CONSTRAINT [FK_MUNICIPIO_DEPARTAMENTO]
GO


