USE [udeo]
GO

/****** Object:  StoredProcedure [dbo].[SP_CAMBIO_INSCRIPCION]    Script Date: 6/06/2024 01:17:03 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO



CREATE PROCEDURE [dbo].[SP_CAMBIO_INSCRIPCION]
  @ID				INT
 ,@CUI				INT
,@NOMBRES			NVARCHAR(100)
,@APELLIDOS			NVARCHAR(100)
,@FECHANAC			DATE
,@TELEFONO			NVARCHAR(8)
,@IDMUNICIPIO		INT
,@DOMICILIO			NVARCHAR(150)
,@IDDIVERSIFICADO	INT
,@IDLICENCIATURA	INT
,@IDJORNADA			INT

AS


BEGIN TRAN 
	
	UPDATE INSCRIPCION
	SET	
		CUI = @CUI,
		NOMBRES			=	@NOMBRES,
		APELLIDOS		=	@APELLIDOS,
		FECHANAC		=	@FECHANAC,
		TELEFONO		=	@TELEFONO,
		IDMUNICIPIO		=	@IDMUNICIPIO,
		DOMICILIO		=	@DOMICILIO,
		IDDIVERSIFICADO =	@IDDIVERSIFICADO,
		IDLICENCIATURA	=	@IDLICENCIATURA,
		IDJORNADA		=	@IDJORNADA
	FROM INSCRIPCION
	WHERE ID = @ID
		

	IF @@ERROR <> 0
	BEGIN
		RAISERROR('PROBLEMAS AL ACTUALIZAR INSCRIPCION',16,1)
		ROLLBACK
		RETURN 99
	END

COMMIT
GO


